### PR TITLE
update layer when data changed also radius changed

### PR DESCRIPTION
**Pull request by heshan0131**
use deep equal to compare whether data has changed. Check if radius has changed to recalculate radius

### CODE REVIEW

**Comment by ibgreen** [comment]
Deep equal may be too expensive here. Immutable.js?

**Comment by heshan0131** [comment]
Do you mean use currentData = Immutable.Map(data) and then Immutable.is(previousData, currentData) to compare? Will it improve performance if we have to convert the array to immutable list every time we compare?

**Comment by ibgreen** [comment]
The "typical" react solution in these cases is to have the component take an immutable map/list as a prop rather than a mutable JS array. Then a shallow compare is sufficient.

It is an API change, but not an unreasonable one.

Since react re-renders the virtual Dom rather vigorously, doing possibly tens of thousands of compares (deep equal on data array) on every render is the concern.

**Comment by heshan0131** [comment]
Yes it would be an API change, and I am assuming we also want to make the change to other overlays besides the scatterplotoverlay

**Comment by ibgreen** [comment]
It's a hack but as an alternative for now, we could add a prop deepCompare, that controls how to compare. Many apps may not mutate their data (either its static or they create new arrays) and don't need deep compare.

**Pull request merged**
